import Cookies from "js-cookie";
import {useEffect, useState} from "react";

/*
  This line is importing two modules from the Wix SDK.
  createClient is a function used to create a new instance of the Wix client, which is used to interact with the Wix APIs.
  OAuthStrategy is a module that provides a method for authenticating API calls using OAuth tokens.
 */
import {createClient, OAuthStrategy} from "@wix/sdk";
/*
    This line is importing the plans module from the Wix Pricing Plans API.
    The plans module provides methods for managing pricing plans.
 */
import {plans} from "@wix/pricing-plans";
/*
    This line is importing the redirects' module.
    The redirects module provides methods for managing URL redirects.
 */
import {redirects} from "@wix/redirects";

import testIds from "@/src/utils/test-ids";

/*
  A Wix client is an instance created using the createClient function from the Wix SDK.
  It's essentially an object that allows you to interact with various Wix APIs, such as the plans and redirects modules in this case.
  Creating a Wix client is necessary because it provides a structured way to interact with Wix APIs.
  It handles the details of making requests to the APIs and processing the responses.
  This allows you to focus on the logic of your application rather than the details of the API.
 */
const myWixClient = createClient({
    // We specify the modules we want to use with the client.
    // In this case, we're using the plans and redirects modules.
    // We also use the redirects module to eventually create a redirect to the checkout page.
    modules: {plans, redirects},

    // We're using the OAuthStrategy for authentication.
    // This strategy requires a client ID and a set of tokens.
    auth: OAuthStrategy({
        // The client ID is a unique identifier for the application.
        // It's used to authenticate the application with the Wix platform.
        // This is a public sample test key.
        // Sign in to add your own key in code sample and see your site data
        clientId: `9e37d7b0-3621-418f-a6b6-b82bdeaf051d`,

        // After creating a Wix client, it can generate, manage, and use tokens. These tokens, even for anonymous site visitors, are used for authentication when interacting with Wix APIs.
        // In this case, we're getting the tokens from a cookie named "session".
        // If the "session" cookie doesn't exist, the tokens default to null, indicating no authentication tokens are available.
        tokens: JSON.parse(Cookies.get("session") || null),
    }),
});

export default function Subscriptions() {
    const [planList, setPlanList] = useState([]);

    // This function fetches a list of public plans.
    async function fetchPlans() {
        // We call the queryPublicPlans method from the plans module of the Wix client.
        // Public plans are visible plans that site visitors can see on the site and purchase.
        const planList = await myWixClient.plans.queryPublicPlans().find();

        // Then, we update the state of the plan list in the React component.
        setPlanList(planList.items);
    }

    // This function creates a redirect to the checkout page for a specific plan.
    async function createRedirect(plan) {
        // We call the createRedirectSession method from the redirects module of the Wix client.
        // This method creates a redirect session to the checkout page.
        // We pass an object that specifies the plan ID for the paidPlansCheckout.
        // We also specify the postFlowUrl to be the current page URL. This is where the user will be redirected after the checkout flow.
        const redirect = await myWixClient.redirects.createRedirectSession({
            paidPlansCheckout: {planId: plan._id},
            callbacks: {postFlowUrl: window.location.href},
        });

        // Finally, we redirect the user to the URL generated by the redirect session.
        window.location = redirect.redirectSession.fullUrl;
    }

    // Fetch the list of plans when the component mounts.
    useEffect(() => {
        fetchPlans();
    }, []);

    return (
        <main data-testid={testIds.SUBSCRIPTIONS_PAGE.CONTAINER}>
            <div>
                <h2>Choose a Plan:</h2>
                {/* We map over the plan list and create a section for each plan. */}
                {planList.map((plan) => {
                    return (
                        <section
                            key={plan._id}
                            data-testid={testIds.SUBSCRIPTIONS_PAGE.PRICING_PLAN}
                            // When the section is clicked, we create a redirect to the checkout page for the plan.
                            onClick={() => createRedirect(plan)}
                        >
                            {/* We display the name of the plan. */}
                            {plan.name}
                        </section>
                    );
                })}
            </div>
        </main>
    );
}
